      # Binary builds (subset, to smoke test that they'll work)
      #
      # NB: If you modify this file, you need to also modify
      # the binary_and_smoke_tests_on_pr variable in
      # pytorch-ci-hud to adjust the list of whitelisted builds
      # at https://github.com/ezyang/pytorch-ci-hud/blob/master/src/BuildHistoryDisplay.js

      - binary_linux_build:
          name: binary_linux_manywheel_2_7mu_cpu_devtoolset7_build
          build_environment: "manywheel 2.7mu cpu devtoolset7"
          requires:
            - setup
          docker_image: "pytorch/manylinux-cuda100"
      - binary_linux_build:
          name: binary_linux_manywheel_3_7m_cu100_devtoolset7_build
          build_environment: "manywheel 3.7m cu100 devtoolset7"
          requires:
            - setup
          docker_image: "pytorch/manylinux-cuda100"
      - binary_linux_build:
          name: binary_linux_conda_2_7_cpu_devtoolset7_build
          build_environment: "conda 2.7 cpu devtoolset7"
          requires:
            - setup
          docker_image: "pytorch/conda-cuda"
      # This binary build is currently broken, see https://github_com/pytorch/pytorch/issues/16710
      # - binary_linux_conda_3_6_cu90_devtoolset7_build
      - binary_linux_build:
          name: binary_linux_libtorch_2_7m_cpu_devtoolset7_shared-with-deps_build
          build_environment: "libtorch 2.7m cpu devtoolset7"
          requires:
            - setup
          libtorch_variant: "shared-with-deps"
          docker_image: "pytorch/manylinux-cuda100"
      - binary_linux_build:
          name: binary_linux_libtorch_2_7m_cpu_gcc5_4_cxx11-abi_shared-with-deps_build
          build_environment: "libtorch 2.7m cpu gcc5.4_cxx11-abi"
          requires:
            - setup
          libtorch_variant: "shared-with-deps"
          docker_image: "pytorch/pytorch-binary-docker-image-ubuntu16.04:latest"
      # TODO we should test a libtorch cuda build, but they take too long
      # - binary_linux_libtorch_2_7m_cu90_devtoolset7_static-without-deps_build
      - binary_mac_build:
          name: binary_macos_wheel_3_6_cpu_build
          build_environment: "wheel 3.6 cpu"
          requires:
            - setup
      - binary_mac_build:
          name: binary_macos_conda_2_7_cpu_build
          build_environment: "conda 2.7 cpu"
          requires:
            - setup
      - binary_mac_build:
          name: binary_macos_libtorch_2_7_cpu_build
          build_environment: "libtorch 2.7 cpu"
          requires:
            - setup

      - binary_linux_test:
          name: binary_linux_manywheel_2_7mu_cpu_devtoolset7_test
          build_environment: "manywheel 2.7mu cpu devtoolset7"
          requires:
            - setup
            - binary_linux_manywheel_2_7mu_cpu_devtoolset7_build
          docker_image: "pytorch/manylinux-cuda100"
      - binary_linux_test:
          name: binary_linux_manywheel_3_7m_cu100_devtoolset7_test
          build_environment: "manywheel 3.7m cu100 devtoolset7"
          requires:
            - setup
            - binary_linux_manywheel_3_7m_cu100_devtoolset7_build
          docker_image: "pytorch/manylinux-cuda100"
          use_cuda_docker_runtime: "1"
          resource_class: gpu.medium
      - binary_linux_test:
          name: binary_linux_conda_2_7_cpu_devtoolset7_test
          build_environment: "conda 2.7 cpu devtoolset7"
          requires:
            - setup
            - binary_linux_conda_2_7_cpu_devtoolset7_build
          docker_image: "pytorch/conda-cuda"
      # This binary build is currently broken, see https://github_com/pytorch/pytorch/issues/16710
      # - binary_linux_conda_3_6_cu90_devtoolset7_test:
      - binary_linux_test:
          name: binary_linux_libtorch_2_7m_cpu_devtoolset7_shared-with-deps_test
          build_environment: "libtorch 2.7m cpu devtoolset7"
          requires:
            - setup
            - binary_linux_libtorch_2_7m_cpu_devtoolset7_shared-with-deps_build
          libtorch_variant: "shared-with-deps"
          docker_image: "pytorch/manylinux-cuda100"
      - binary_linux_test:
          name: binary_linux_libtorch_2_7m_cpu_gcc5_4_cxx11-abi_shared-with-deps_test
          build_environment: "libtorch 2.7m cpu gcc5.4_cxx11-abi"
          requires:
            - setup
            - binary_linux_libtorch_2_7m_cpu_gcc5_4_cxx11-abi_shared-with-deps_build
          libtorch_variant: "shared-with-deps"
          docker_image: "pytorch/pytorch-binary-docker-image-ubuntu16.04:latest"

